In [32]:
%run ../setup/config

Box(children=(Label(value='Environment'), Dropdown(options=('dev', 'prod'), value='dev')))

Box(children=(Label(value='Cluster ID (vacío = serverless)'), Text(value='')))

In [33]:

from pyspark.sql import functions as F

In [34]:
df_menu = (
    spark.read
    .format("csv")
    .option("header", "true")
    .schema(BRONZE_MENU_SCHEMA)
    .load(LANDING_MENU_PATH)
)

In [35]:
df_bronze_menu = (
    df_menu
    .withColumn("_source_file", F.col("_metadata.file_path"))
    .withColumn("_ingestion_timestamp", F.current_timestamp())
)

In [36]:
(
    df_bronze_menu.write
    .format("delta")
    .mode("overwrite")
    .option("mergeSchema", "true")
    .saveAsTable(BRONZE_MENU_FULL_TABLE)
)

In [37]:
display(
    spark.table(BRONZE_MENU_FULL_TABLE)
    .orderBy("menu_item_id")
)

DataFrame[menu_item_id: int, item_name: string, category: string, price: double, _source_file: string, _ingestion_timestamp: timestamp]

In [38]:
display(
    spark.table(BRONZE_MENU_FULL_TABLE)
    .filter(F.col("menu_item_id") == 132)
)

DataFrame[menu_item_id: int, item_name: string, category: string, price: double, _source_file: string, _ingestion_timestamp: timestamp]